spring:
  application:
    name: iltuo
  config:
    import: classpath:application-secret.yml
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  jackson:
    time-zone: Asia/Seoul
server:
  port: 8081